networks:
  webnet:

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - webnet
  db:
    image: mysql:5.7
    environment:
    MYSQL_ROOT_PASSWORD: example
    networks:
      - webnet
